/**
 * NEXUS DEX - Unified Swap Widget (OKX DEX edition)
 *
 * Swap engine: OKX DEX API
 *   Solana swaps  -> /api/okx/dex/aggregator/swap-instruction
 *   EVM swaps     -> /api/okx/dex/aggregator/swap
 * 
 * Price data: DexScreener (replaces LiFi + Helius)
 * Token search: OKX (Solana) + DexScreener (all chains)
 * OKX referrer tag added to all OKX requests.
 * Fees injected server-side in server.js.
 */

import React, { useState, useEffect, useCallback, useMemo, useRef } from 'react';
import { Buffer } from 'buffer';
import { useWallet, useConnection } from '@solana/wallet-adapter-react';
import { useNexusWallet } from '../WalletContext.js';
import { useAccount, useWalletClient, useBalance, useSwitchChain, usePublicClient } from 'wagmi';
import {
  VersionedTransaction, PublicKey, LAMPORTS_PER_SOL,
  TransactionInstruction, TransactionMessage, AddressLookupTableAccount,
} from '@solana/web3.js';

const OKX_REFERRER = 'nexus-dex';
const PLATFORM_FEE = 0.03;
const SAFETY_FEE   = 0.02;
const TOTAL_FEE    = PLATFORM_FEE + SAFETY_FEE;
const OKX_SOL_NATIVE = '11111111111111111111111111111111';
const OKX_EVM_NATIVE = '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE';
const NATIVE_EVM = '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee';
const WSOL_MINT  = 'So11111111111111111111111111111111111111112';

const OKX_EVM_CHAINS = new Set([1, 10, 56, 130, 137, 146, 324, 1101, 5000, 8453, 34443, 42161, 43114, 57073, 59144, 80094, 81457, 534352, 1329, 2741]);

const SOL_RESERVE_LAMPORTS   = 5_000_000;
const EVM_NATIVE_RESERVE_PCT = 0.005;
const QUOTE_DEBOUNCE_MS      = 250;
const PRICE_CACHE_TTL_MS     = 60_000;

const CHAIN_NAMES = { 1:'Ethereum',10:'Optimism',56:'BNB Chain',100:'Gnosis',130:'Unichain',137:'Polygon',146:'Sonic',250:'Fantom',324:'zkSync Era',2741:'Abstract',5000:'Mantle',8453:'Base',34443:'Mode',42161:'Arbitrum',43114:'Avalanche',57073:'Ink',59144:'Linea',80094:'Berachain',81457:'Blast',534352:'Scroll',1329:'SEI',1101:'Polygon zkEVM' };
const CHAIN_SHORT = { 1:'ETH',10:'OP',56:'BNB',130:'UNI',137:'POL',146:'SONIC',324:'zkSync',2741:'ABS',5000:'MNT',8453:'BASE',34443:'MODE',42161:'ARB',43114:'AVAX',57073:'INK',59144:'LINEA',80094:'BERA',81457:'BLAST',534352:'SCROLL',1329:'SEI',1101:'POL-ZK' };

const USDC_BY_CHAIN = { 1:'0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',10:'0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85',56:'0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d',137:'0x3c499c542cef5e3811e1192ce70d8cc03d5c3359',8453:'0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',42161:'0xaf88d065e77c8cC2239327C5EDb3A432268e5831',43114:'0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E' };
const USDC_SOLANA = 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v';
const DEXSCREENER_BASE = '/api/dexscreener';

const DEFAULT_BUY_PRESETS  = [25,50,100,250,500];
const DEFAULT_SELL_PRESETS = [50,100];
const PRESETS_LS_KEY = 'nexus_presets_v2';
const LAST_PAIR_LS_KEY = 'nexus_last_pair_v1';

const C = { bg:'#03060f',card:'#080d1a',card2:'#0c1220',card3:'#111d30',border:'rgba(0,229,255,0.10)',borderHi:'rgba(0,229,255,0.25)',accent:'#00e5ff',green:'#00ffa3',red:'#ff3b6b',text:'#cdd6f4',muted:'#586994',muted2:'#2e3f5e',buyGrad:'linear-gradient(135deg,#00e5ff,#0055ff)',sellGrad:'linear-gradient(135deg,#ff3b6b,#cc1144)',privy:'#a855f7' };

const POPULAR_TOKENS = [
  { mint:WSOL_MINT,symbol:'SOL',name:'Solana',decimals:9,chain:'solana',logoURI:'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/So11111111111111111111111111111111111111112/logo.png'},
  { mint:USDC_SOLANA,symbol:'USDC',name:'USD Coin',decimals:6,chain:'solana'},
  { address:NATIVE_EVM,chainId:1,symbol:'ETH',name:'Ethereum',decimals:18,chain:'evm'},
  { address:NATIVE_EVM,chainId:8453,symbol:'ETH',name:'ETH (Base)',decimals:18,chain:'evm'},
  { address:NATIVE_EVM,chainId:42161,symbol:'ETH',name:'ETH (Arbitrum)',decimals:18,chain:'evm'},
  { address:NATIVE_EVM,chainId:10,symbol:'ETH',name:'ETH (Optimism)',decimals:18,chain:'evm'},
  { address:NATIVE_EVM,chainId:56,symbol:'BNB',name:'BNB',decimals:18,chain:'evm'},
  { address:NATIVE_EVM,chainId:137,symbol:'POL',name:'Polygon',decimals:18,chain:'evm'},
  { address:NATIVE_EVM,chainId:43114,symbol:'AVAX',name:'Avalanche',decimals:18,chain:'evm'},
  { address:USDC_BY_CHAIN[1],chainId:1,symbol:'USDC',name:'USDC (ETH)',decimals:6,chain:'evm'},
  { address:USDC_BY_CHAIN[8453],chainId:8453,symbol:'USDC',name:'USDC (Base)',decimals:6,chain:'evm'},
  { address:USDC_BY_CHAIN[42161],chainId:42161,symbol:'USDC',name:'USDC (Arbitrum)',decimals:6,chain:'evm'},
];

const _NATIVE_BY_CHAIN = { 1:{symbol:'ETH',name:'Ethereum'},56:{symbol:'BNB',name:'BNB'},137:{symbol:'POL',name:'Polygon'},43114:{symbol:'AVAX',name:'Avalanche'},8453:{symbol:'ETH',name:'ETH (Base)'},42161:{symbol:'ETH',name:'ETH (Arbitrum)'},10:{symbol:'ETH',name:'ETH (Optimism)'} };

function safeBigInt(v){if(v==null)return BigInt(0);if(typeof v==='bigint')return v;if(typeof v==='number')return Number.isFinite(v)?BigInt(Math.trunc(v)):BigInt(0);let s=String(v).trim();if(!s)return BigInt(0);if(/^-?0x[0-9a-f]+$/i.test(s))return BigInt(s);if(/^-?\d+$/.test(s))return BigInt(s);const n=Number(s);return Number.isFinite(n)?BigInt(Math.trunc(n)):BigInt(0);}
function tokensEqual(a,b){if(!a||!b)return false;if(a.chain==='solana'&&b.chain==='solana')return a.mint===b.mint;if(a.chain==='evm'&&b.chain==='evm')return a.chainId===b.chainId&&(a.address||'').toLowerCase()===(b.address||'').toLowerCase();return false;}
function fmtUsd(n,d=2){if(n==null||isNaN(n))return'-';const v=Number(n);if(v>=1e9)return'$'+(v/1e9).toFixed(2)+'B';if(v>=1e6)return'$'+(v/1e6).toFixed(2)+'M';if(v>=1000)return'$'+v.toLocaleString('en-US',{maximumFractionDigits:d});if(v>=1)return'$'+v.toFixed(d);if(v>0)return'$'+v.toFixed(6);return'$0.00';}
function fmtTokenAmount(n,d=4){if(n==null||isNaN(n))return'0';const v=Number(n);if(v>=1e9)return(v/1e9).toFixed(2)+'B';if(v>=1e6)return(v/1e6).toFixed(2)+'M';if(v>=1000)return v.toLocaleString('en-US',{maximumFractionDigits:2});return v.toFixed(d);}
function shortAddr(a,h=4,t=4){if(!a||a.length<h+t)return a||'';return a.slice(0,h)+'\u2026'+a.slice(-t);}
function isValidSolMint(s){return!!s&&s.length>=32&&s.length<=44&&/^[1-9A-HJ-NP-Za-km-z]+$/.test(s);}
function isValidEvmAddr(s){return!!s&&/^0x[0-9a-fA-F]{40}$/.test(s);}
function toRawAmount(s,dec){if(!s||dec==null)return'0';let v=String(s).trim().replace(/,/g,'.').replace(/^\+/,'');if(!v||v.startsWith('-'))return'0';if(/e/i.test(v)){const n=Number(v);if(!Number.isFinite(n)||n<0)return'0';v=n.toFixed(Math.max(Number(dec)||0,20));}const d=Math.floor(Number(dec));if(!Number.isFinite(d)||d<0||d>18)return'0';const[w,f='']=v.split('.');const sw=(w||'0').replace(/[^\d]/g,'').replace(/^0+(?=\d)/,'')||'0';const ft=(f||'').replace(/[^\d]/g,'').slice(0,d);const fp=(ft+'0'.repeat(d)).slice(0,d)||'0';try{return(BigInt(sw)*(10n**BigInt(d))+BigInt(fp)).toString();}catch{return'0';}}

function normalizeToken(input){if(!input)return null;if(input.chain==='solana'&&input.mint)return input;if(input.chain==='evm'&&input.address&&input.chainId)return input;const logo=input.logoURI||input.image||input.thumbnail||null;const sym=input.symbol||'TOKEN';const name=input.name||sym;const evm=input.address||input.contractAddress||null;if(evm&&isValidEvmAddr(evm))return{chain:'evm',address:evm,chainId:input.chainId||1,symbol:sym,name,decimals:input.decimals||18,logoURI:logo};const solMint=input.mint||(input.isSolanaToken?input.id:null);if(solMint&&isValidSolMint(solMint))return{chain:'solana',mint:solMint,symbol:sym,name,decimals:input.decimals||6,logoURI:logo};return null;}
function nativeOfChain(cid){if(cid==='solana')return POPULAR_TOKENS.find(t=>t.mint===WSOL_MINT);const p=POPULAR_TOKENS.find(t=>t.chain==='evm'&&t.chainId===cid&&t.address===NATIVE_EVM);if(p)return p;const m=_NATIVE_BY_CHAIN[cid];if(!m)return null;return{chain:'evm',address:NATIVE_EVM,chainId:cid,symbol:m.symbol,name:m.name,decimals:18,logoURI:null};}
function usdcOfChain(cid){if(cid==='solana')return POPULAR_TOKENS.find(t=>t.mint===USDC_SOLANA);const a=USDC_BY_CHAIN[cid];if(!a)return null;return POPULAR_TOKENS.find(t=>t.chain==='evm'&&t.chainId===cid&&(t.address||'').toLowerCase()===a.toLowerCase())||{chain:'evm',address:a,chainId:cid,symbol:'USDC',name:'USDC',decimals:6,logoURI:null};}
function pickDistinct(target,cands){for(const c of cands){if(c&&(!target||!tokensEqual(c,target)))return c;}return null;}
function defaultTokenPair({mode,viewedToken,lastFromToken,walletState}){const ws=walletState||{};const viewed=viewedToken?normalizeToken(viewedToken):null;if(mode==='buy'&&viewed){const c=viewed.chain==='solana'?'solana':viewed.chainId;const f=pickDistinct(viewed,[lastFromToken,nativeOfChain(c),usdcOfChain(c),POPULAR_TOKENS[0]]);return{fromToken:f||POPULAR_TOKENS[0],toToken:viewed};}if(mode==='sell'&&viewed){const c=viewed.chain==='solana'?'solana':viewed.chainId;const t=pickDistinct(viewed,[usdcOfChain(c),nativeOfChain(c),POPULAR_TOKENS[1],POPULAR_TOKENS[0]]);return{fromToken:viewed,toToken:t||POPULAR_TOKENS[1]};}if(lastFromToken){const c=lastFromToken.chain==='solana'?'solana':lastFromToken.chainId;const u=usdcOfChain(c);if(u&&!tokensEqual(u,lastFromToken))return{fromToken:lastFromToken,toToken:u};}if(ws.solConnected)return{fromToken:nativeOfChain('solana'),toToken:usdcOfChain('solana')};if(ws.evmConnected&&ws.evmChainId){const n=nativeOfChain(ws.evmChainId),u=usdcOfChain(ws.evmChainId)||usdcOfChain('solana');if(n&&u)return{fromToken:n,toToken:u};}return{fromToken:nativeOfChain('solana'),toToken:usdcOfChain('solana')};}
function pickRoute(from,to){if(!from||!to)return'unsupported';if(from.chain==='solana'&&to.chain==='solana')return'okx-sol';if(from.chain==='evm'&&to.chain==='evm'&&from.chainId===to.chainId&&OKX_EVM_CHAINS.has(from.chainId))return'okx-evm';return'unsupported';}
function toOkxSolAddress(m){return m===WSOL_MINT?OKX_SOL_NATIVE:m;}
function toOkxEvmAddress(a){return(a||'').toLowerCase()===NATIVE_EVM?OKX_EVM_NATIVE:a;}

const _dsCache=new Map();
function dsCacheKey(t){if(!t)return null;return t.chain==='solana'?'sol:'+t.mint:'evm:'+t.chainId+':'+(t.address||'').toLowerCase();}
function getCachedDsPrice(t){const k=dsCacheKey(t);if(!k)return null;const e=_dsCache.get(k);if(!e)return null;if(Date.now()-e.ts>PRICE_CACHE_TTL_MS){_dsCache.delete(k);return null;}return e.price;}
function setCachedDsPrice(t,p){const k=dsCacheKey(t);if(!k||!(p>0))return;_dsCache.set(k,{price:Number(p),ts:Date.now()});}
async function fetchDsTokenPrice(t){if(!t)return null;const c=getCachedDsPrice(t);if(c!=null)return c;try{const a=t.chain==='solana'?t.mint:t.address;const r=await fetch(DEXSCREENER_BASE+'/latest/dex/tokens/'+encodeURIComponent(a));const d=await r.json().catch(()=>null);if(d&&d.pairs&&d.pairs.length>0){let best=null;for(const p of d.pairs){const pr=Number(p.priceUsd||0);if(pr>0&&(!best||(p.liquidity?.usd||0)>(best.liquidity?.usd||0)))best=p;}if(best){const pr=Number(best.priceUsd||0);if(pr>0){setCachedDsPrice(t,pr);return pr;}}}}catch{}return null;}
async function fetchDsSearch(q){try{const r=await fetch(DEXSCREENER_BASE+'/latest/dex/search?q='+encodeURIComponent(q));const d=await r.json().catch(()=>null);if(!d||!Array.isArray(d.pairs))return[];const seen=new Set();const out=[];for(const p of d.pairs){const bt=p.baseToken||{};const addr=bt.address||'';if(!addr||seen.has(addr.toLowerCase()))continue;seen.add(addr.toLowerCase());const isSol=p.chainId==='solana';out.push({chain:isSol?'solana':'evm',mint:isSol?addr:undefined,address:isSol?undefined:addr,chainId:isSol?undefined:(CHAIN_SHORT[p.chainId]?Number(Object.keys(CHAIN_SHORT).find(k=>CHAIN_SHORT[k]===p.chainId))||1:1),symbol:bt.symbol||'???',name:bt.name||bt.symbol||'Unknown',decimals:isSol?6:(bt.decimals||18),logoURI:bt.imgUrl||p.info?.imageUrl||null});}return out.slice(0,40);}catch{return[];}}

let _okxCache=null;let _okxLoading=null;
function loadOkxSolTokens(){if(_okxCache)return Promise.resolve(_okxCache);if(_okxLoading)return _okxLoading;_okxLoading=fetch('/api/okx/dex/aggregator/all-tokens?chainIndex=501').then(r=>r.ok?r.json():{data:[]}).catch(()=>({data:[]})).then(j=>{const t=(j.data||[]).map(t=>({chain:'solana',mint:t.tokenContractAddress,symbol:t.tokenSymbol||'',name:t.tokenName||t.tokenSymbol||'',decimals:parseInt(t.decimals)||6,logoURI:t.tokenLogoUrl||null})).filter(t=>isValidSolMint(t.mint)&&t.symbol);_okxCache=t;_okxLoading=null;return t;});return _okxLoading;}

async function fetchOkxSolSwap({fromMint,toMint,amount,slippage,userWallet,signal}){const p=new URLSearchParams({chainIndex:'501',fromTokenAddress:toOkxSolAddress(fromMint),toTokenAddress:toOkxSolAddress(toMint),amount:String(amount),slippagePercent:(slippage/100).toFixed(4),userWalletAddress:userWallet,referrer:OKX_REFERRER});const r=await fetch('/api/okx/dex/aggregator/swap-instruction?'+p.toString(),{signal});const j=await r.json();if(j.code!=='0'||!j.data||!j.data[0])throw new Error(j.msg||'OKX swap-instruction failed');return j.data[0];}
async function fetchOkxEvmSwap({chainId,fromAddress,toAddress,amount,slippage,userWallet,signal}){const p=new URLSearchParams({chainIndex:String(chainId),fromTokenAddress:toOkxEvmAddress(fromAddress),toTokenAddress:toOkxEvmAddress(toAddress),amount:String(amount),slippagePercent:(slippage/100).toFixed(4),userWalletAddress:userWallet,referrer:OKX_REFERRER});const r=await fetch('/api/okx/dex/aggregator/swap?'+p.toString(),{signal});const j=await r.json();if(j.code!=='0'||!j.data||!j.data[0])throw new Error(j.msg||'OKX EVM swap failed');return j.data[0];}
async function fetchOkxEvmApproval({chainId,tokenAddress,amount}){try{const p=new URLSearchParams({chainIndex:String(chainId),tokenContractAddress:tokenAddress,approveAmount:String(amount),referrer:OKX_REFERRER});const r=await fetch('/api/okx/dex/aggregator/approve-transaction?'+p.toString());const j=await r.json();if(j.code!=='0'||!j.data||!j.data[0])return null;return j.data[0];}catch{return null;}}
function deserializeOkxIx(ix){return new TransactionInstruction({programId:new PublicKey(ix.programId),keys:(ix.accounts||[]).map(a=>({pubkey:new PublicKey(a.pubkey),isSigner:!!a.isSigner,isWritable:!!a.isWritable})),data:Buffer.from(ix.data||'','base64')});}
async function buildOkxSolTx({connection,userPubkey,swapData}){const ixs=(swapData.instructionLists||[]).map(deserializeOkxIx);const lta=Array.isArray(swapData.addressLookupTableAccount)?swapData.addressLookupTableAccount:[];const lts=(await Promise.all(lta.map(async a=>{try{const acct=await connection.getAccountInfo(new PublicKey(a));if(!acct)return null;return new AddressLookupTableAccount({key:new PublicKey(a),state:AddressLookupTableAccount.deserialize(acct.data)});}catch{return null}}))).filter(Boolean);const{bh}=await connection.getLatestBlockhash('finalized');return new VersionedTransaction(new TransactionMessage({payerKey:userPubkey,recentBlockhash:bh,instructions:ixs}).compileToV0Message(lts));}

function loadPresets(){try{const r=localStorage.getItem(PRESETS_LS_KEY);if(!r)return{buy:DEFAULT_BUY_PRESETS.slice(),sell:DEFAULT_SELL_PRESETS.slice()};const p=JSON.parse(r);return{buy:Array.isArray(p.buy)&&p.buy.length>=2?p.buy:DEFAULT_BUY_PRESETS.slice(),sell:Array.isArray(p.sell)&&p.sell.length>=1?p.sell:DEFAULT_SELL_PRESETS.slice()};}catch{return{buy:DEFAULT_BUY_PRESETS.slice(),sell:DEFAULT_SELL_PRESETS.slice()};}}
function savePresets(p){try{localStorage.setItem(PRESETS_LS_KEY,JSON.stringify(p));}catch{}}
function loadLastPair(){try{const v=JSON.parse(localStorage.getItem(LAST_PAIR_LS_KEY)||'null');return(!v||!v.from)?null:v;}catch{return null;}}
function saveLastPair(from,to){if(!from||!to)return;try{localStorage.setItem(LAST_PAIR_LS_KEY,JSON.stringify({from,to,ts:Date.now()}));}catch{}}
function maxSafeAmount({balance,isNative}){if(!balance||balance<=0)return 0;return isNative?balance*(1-EVM_NATIVE_RESERVE_PCT):balance;}
function maxSafeSolBalance(lamports){return lamports?Math.max(0,lamports-SOL_RESERVE_LAMPORTS)/LAMPORTS_PER_SOL:0;}

function ChainBadge({token}){if(!token)return null;const l=token.chain==='solana'?'SOL':(CHAIN_SHORT[token.chainId]||'EVM');const c=token.chain==='solana'?'#9945ff':'#627eea';return<span style={{fontSize:9,color:c,background:c+'22',border:'1px solid '+c+'44',borderRadius:4,padding:'1px 5px',marginLeft:4,fontWeight:700}}>{l}</span>;}
function TokenIcon({token,size=32}){const[err,setErr]=useState(false);if(token&&token.logoURI&&!err)return<img src={token.logoURI} alt="" style={{width:size,height:size,borderRadius:'50%',flexShrink:0}} onError={()=>setErr(true)}/>;const ch=(token&&token.symbol)?token.symbol.charAt(0).toUpperCase():'?';return<div style={{width:size,height:size,borderRadius:'50%',flexShrink:0,background:'rgba(0,229,255,.1)',border:'1px solid rgba(0,229,255,.2)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:Math.round(size*.4),fontWeight:700,color:C.accent}}>{ch}</div>;}

let _bl=0;
function useBodyScrollLock(open){useEffect(()=>{if(!open)return;if(typeof document==='undefined')return;if(_bl===0)document.body.classList.add('nexus-scroll-locked');_bl++;return()=>{_bl=Math.max(0,_bl-1);if(_bl===0)document.body.classList.remove('nexus-scroll-locked');};},[open]);}
function useEscapeKey(open,handler){useEffect(()=>{if(!open)return;const onKey=e=>{if(e.key==='Escape'){e.stopPropagation();handler?.();}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[open,handler]);}

function TokenSelectModal({open,onClose,onSelect}){const[q,setQ]=useState('');const[ci,setCi]=useState('');const[sr,setSr]=useState([]);const[disc,setDisc]=useState(false);const[ct,setCt]=useState(null);const[cl,setCl]=useState(false);const{chainId:evmChainId}=useAccount();const pc=usePublicClient({chainId:evmChainId||1});
  useEffect(()=>{const t=q.trim();if(!t){setSr([]);return;}const h=setTimeout(async()=>{const sol=(_okxCache||[]).filter(tk=>(tk.symbol&&tk.symbol.toLowerCase().includes(t.toLowerCase()))||(tk.mint&&tk.mint===t)).slice(0,30);const pop=POPULAR_TOKENS.filter(tk=>tk.symbol&&tk.symbol.toLowerCase().includes(t.toLowerCase()));setSr([...sol,...pop]);},200);return()=>clearTimeout(h);},[q]);
  const dr=useRef(0);
  useEffect(()=>{const t=q.trim();if(!t||t.length<2||isValidSolMint(t)||isValidEvmAddr(t)){setDisc(false);return;}const rid=++dr.current;setDisc(true);const h=setTimeout(async()=>{const ds=await fetchDsSearch(t);if(dr.current!==rid)return;const seen=new Set(sr.map(tk=>(tk.mint||tk.address||'').toLowerCase()));const nt=ds.filter(tk=>!seen.has((tk.mint||tk.address||'').toLowerCase()));if(nt.length>0)setSr(p=>[...p,...nt].slice(0,60));setDisc(false);},400);return()=>clearTimeout(h);},[q]);
  useEffect(()=>{const a=ci.trim();if(!a){setCt(null);setCl(false);return;}if(!isValidSolMint(a)&&!isValidEvmAddr(a)){setCt(null);return;}setCl(true);let c=false;(async()=>{try{if(isValidSolMint(a)){const cd=(_okxCache||[]).find(tk=>tk.mint===a);if(!c){setCt(cd||{chain:'solana',mint:a,symbol:shortAddr(a),name:'Custom Token',decimals:6,logoURI:null});setCl(false);}}else{let sym=shortAddr(a),dec=18;try{if(pc){const[d,s]=await Promise.allSettled([pc.readContract({address:a,abi:[{name:'decimals',type:'function',stateMutability:'view',inputs:[],outputs:[{type:'uint8'}]}],functionName:'decimals'}),pc.readContract({address:a,abi:[{name:'symbol',type:'function',stateMutability:'view',inputs:[],outputs:[{type:'string'}]}],functionName:'symbol'})]);if(d.status==='fulfilled')dec=Number(d.value);if(s.status==='fulfilled'&&s.value)sym=s.value;}}catch{}if(!c){setCt({chain:'evm',address:a,chainId:evmChainId||1,symbol:sym,name:'Custom Token',decimals:dec,logoURI:null});setCl(false);}}}catch{if(!c){setCt(null);setCl(false);}}})();return()=>{c=true;};},[ci,evmChainId,pc]);
  const close=()=>{setQ('');setCi('');setCt(null);setSr([]);onClose();};useBodyScrollLock(open);useEscapeKey(open,close);const hs=useCallback(t=>{onSelect(t);close();},[onSelect,close]);const disp=q.trim()?sr:POPULAR_TOKENS;
  if(!open)return null;
  return(
    <><div onClick={close} style={{position:'fixed',inset:0,zIndex:499,background:'rgba(0,0,0,.78)'}}/>
    <div style={{position:'fixed',top:'50%',left:'50%',transform:'translate(-50%,-50%)',zIndex:500,background:C.card,border:'1px solid '+C.borderHi,borderRadius:18,width:'94vw',maxWidth:440,maxHeight:'min(85vh, 100dvh)',display:'flex',flexDirection:'column',boxShadow:'0 24px 80px rgba(0,0,0,.95)'}}>
      <div style={{padding:'16px 16px 10px',borderBottom:'1px solid '+C.border,flexShrink:0}}>
        <div style={{display:'flex',justifyContent:'space-between',marginBottom:10}}><div style={{color:'#fff',fontWeight:700,fontSize:16}}>Select Token</div><button onClick={close} style={{background:'none',border:'none',color:C.muted,cursor:'pointer',fontSize:22,padding:4}}>x</button></div>
        <input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, symbol..." style={{width:'100%',background:C.card2,border:'1px solid '+C.border,borderRadius:8,padding:'10px 12px',color:'#fff',fontSize:13,outline:'none',marginBottom:8,fontFamily:'Syne, sans-serif'}}/>
        <input value={ci} onChange={e=>setCi(e.target.value)} placeholder="Or paste contract address..." style={{width:'100%',background:C.card2,border:'1px solid rgba(0,229,255,.2)',borderRadius:8,padding:'10px 12px',color:C.accent,fontSize:12,outline:'none',fontFamily:'monospace'}}/>
        {cl&&<div style={{color:C.muted,fontSize:11,marginTop:6}}>Looking up...</div>}
        {ct&&!cl&&(<div onClick={()=>hs(ct)} style={{marginTop:8,padding:'10px 12px',background:'rgba(0,229,255,.08)',border:'1px solid rgba(0,229,255,.3)',borderRadius:8,cursor:'pointer',display:'flex',alignItems:'center',gap:10}}><TokenIcon token={ct} size={28}/><div style={{flex:1}}><span style={{color:'#fff',fontWeight:700,fontSize:13}}>{ct.symbol}</span></div><span style={{color:C.accent,fontSize:11}}>Select</span></div>)}
      </div>
      <div style={{overflowY:'auto',flex:1}}>
        {!q&&<div style={{padding:'8px 16px 4px',fontSize:10,color:C.muted,fontWeight:700}}>POPULAR</div>}
        {disp.length===0&&<div style={{padding:24,textAlign:'center',color:C.muted}}>{disc?'Searching...':'No matches'}</div>}
        {disp.map((t,i)=>(<div key={(t.mint||t.address||'')+i} onClick={()=>hs(t)} style={{padding:'12px 16px',cursor:'pointer',display:'flex',alignItems:'center',gap:10,borderBottom:'1px solid rgba(255,255,255,.03)'}}><TokenIcon token={t} size={32}/><div style={{flex:1}}><div style={{display:'flex',alignItems:'center'}}><span style={{color:'#fff',fontWeight:700,fontSize:13}}>{t.symbol}</span><ChainBadge token={t}/></div><div style={{color:C.muted,fontSize:11}}>{t.name}</div></div></div>))}
      </div>
    </div></>
  );
}

/* ===== MAIN SWAP WIDGET ===== */
export default function SwapWidget({onConnectWallet,defaultFromToken,defaultToToken,compact=false,mode:modeProp='swap',presets:presetsProp,onPresetsChange,onStatusChange}){
  const{publicKey:extPk,sendTransaction:extSendTx,connected:solCon}=useWallet();const{connection}=useConnection();const{address:evmAddr,isConnected:evmCon,chainId:evmCid}=useAccount();const{data:wc}=useWalletClient();const{switchChain,switchChainAsync}=useSwitchChain();const nexus=useNexusWallet();const{activeWalletKind,privyEmbeddedSol,privyEmbeddedEvm,loginPrivy}=nexus;
  const pubkey=useMemo(()=>{if(extPk)return extPk;if(privyEmbeddedSol?.address){try{return new PublicKey(privyEmbeddedSol.address);}catch{return null;}}return null;},[extPk,privyEmbeddedSol]);
  const hasSol=!!(solCon||(privyEmbeddedSol&&pubkey));const hasEvm=!!(evmCon||(privyEmbeddedEvm&&privyEmbeddedEvm.address));const effEvm=evmAddr||(privyEmbeddedEvm?.address)||null;const wcon=!!(solCon||evmCon||hasSol||hasEvm);
  const wcRef=useRef(wc);useEffect(()=>{wcRef.current=wc;},[wc]);const cidRef=useRef(evmCid);useEffect(()=>{cidRef.current=evmCid;},[evmCid]);const pcRef=useRef(null);
  const sendTx=useCallback(async(tx,conn,opts)=>{if(activeWalletKind==='privy'&&privyEmbeddedSol){if(typeof privyEmbeddedSol.sendTransaction==='function')return privyEmbeddedSol.sendTransaction(tx,conn,opts);if(typeof privyEmbeddedSol.signTransaction==='function'){const s=await privyEmbeddedSol.signTransaction(tx);return conn.sendRawTransaction(s.serialize(),opts||{});}throw new Error('No sign method');}return extSendTx(tx,conn,opts);},[activeWalletKind,privyEmbeddedSol,extSendTx]);
  const ensureChain=useCallback(async(tid)=>{if(cidRef.current===tid)return true;try{if(switchChainAsync)await switchChainAsync({chainId:tid});else if(switchChain)switchChain({chainId:tid});}catch{throw new Error('Switch to '+(CHAIN_NAMES[tid]||'correct chain'));}for(let i=0;i<80;i++){if(cidRef.current===tid)return true;await new Promise(r=>setTimeout(r,100));}throw new Error('Chain switch failed');},[switchChain,switchChainAsync]);
  const ip=useMemo(()=>{if(defaultFromToken||defaultToToken){const ws={solConnected:solCon,evmConnected:evmCon,evmChainId:evmCid};const p=defaultTokenPair({mode:modeProp,viewedToken:defaultToToken||defaultFromToken,lastFromToken:null,walletState:ws});return{fromToken:defaultFromToken?normalizeToken(defaultFromToken):p.fromToken,toToken:defaultToToken?normalizeToken(defaultToToken):p.toToken};}const last=loadLastPair();const ws={solConnected:solCon,evmConnected:evmCon,evmChainId:evmCid};return defaultTokenPair({mode:modeProp,viewedToken:null,lastFromToken:last?.from?normalizeToken(last.from):null,walletState:ws});},[]);
  const[ft,setFt]=useState(ip.fromToken||POPULAR_TOKENS[0]);const[tt,setTt]=useState(ip.toToken||POPULAR_TOKENS[1]);const[fa,setFa]=useState('');const[sl,setSl]=useState(.5);const utRef=useRef(false);
  const[quote,setQ]=useState(null);const[qe,setQe]=useState('');const[qs,setQs]=useState(false);
  const[ss,setSs]=useState('idle');const[stx,setStx]=useState(null);const[se,setSe]=useState('');const[ps,setPs]=useState(false);const[stuck,setStuck]=useState(false);const stuckRef=useRef(null);
  useEffect(()=>{if(ss==='loading'){setStuck(false);stuckRef.current=setTimeout(()=>setStuck(true),30000);}else{if(stuckRef.current)clearTimeout(stuckRef.current);setStuck(false);}return()=>{if(stuckRef.current)clearTimeout(stuckRef.current);};},[ss]);
  useEffect(()=>{onStatusChange?.(ss);},[ss,onStatusChange]);
  const[sbl,setSbl]=useState(null);const[ssb,setSsb]=useState(null);
  const[pl,setPl]=useState(()=>presetsProp||loadPresets());const presets=presetsProp||pl;const setPresets=useCallback(p=>{if(onPresetsChange)onPresetsChange(p);else{setPl(p);savePresets(p);}},[onPresetsChange]);const[peo,setPeo]=useState(false);const[fso,setFso]=useState(false);const[tso,setTso]=useState(false);
  const route=useMemo(()=>pickRoute(ft,tt),[ft,tt]);const isSup=route!=='unsupported';const needsSol=route==='okx-sol';const needsEvm=route==='okx-evm';const hasNeeded=(needsSol&&hasSol)||(needsEvm&&hasEvm);const isNativeEvm=ft?.chain==='evm'&&(ft.address||'').toLowerCase()===NATIVE_EVM;const needsApproval=ft?.chain==='evm'&&!isNativeEvm&&route==='okx-evm';
  const pclient=usePublicClient({chainId:ft?.chain==='evm'?ft.chainId:undefined});useEffect(()=>{pcRef.current=pclient;},[pclient]);
  const{data:evmBal,refetch:refEvm}=useBalance({address:effEvm,token:ft?.chain==='evm'&&!isNativeEvm?ft.address:undefined,chainId:ft?.chain==='evm'?ft.chainId:undefined,query:{enabled:!!effEvm&&ft?.chain==='evm'}});
  useEffect(()=>{if(!pubkey||!connection){setSbl(null);setSsb(null);return;}let c=false;connection.getBalance(pubkey).then(b=>{if(!c)setSbl(b);}).catch(()=>{});if(ft?.chain==='solana'&&ft.mint!==WSOL_MINT){connection.getParsedTokenAccountsByOwner(pubkey,{mint:new PublicKey(ft.mint)}).then(a=>{if(!c)setSsb(a.value.length?a.value[0].account.data.parsed.info.tokenAmount.uiAmount:0);}).catch(()=>{});}else{setSsb(null);}return()=>{c=true;};},[pubkey,connection,ft]);
  useEffect(()=>{if(ss!=='success')return;refEvm?.();if(pubkey&&connection&&ft?.chain==='solana'){connection.getBalance(pubkey).then(setSbl).catch(()=>{});if(ft.mint!==WSOL_MINT)connection.getParsedTokenAccountsByOwner(pubkey,{mint:new PublicKey(ft.mint)}).then(a=>setSsb(a.value.length?a.value[0].account.data.parsed.info.tokenAmount.uiAmount:0)).catch(()=>{});}},[ss]);
  const[fp,setFp]=useState(null);const[tp,setTp]=useState(null);
  useEffect(()=>{let c=false;fetchDsTokenPrice(ft).then(p=>{if(!c)setFp(p);});return()=>{c=true;};},[ft]);
  useEffect(()=>{let c=false;fetchDsTokenPrice(tt).then(p=>{if(!c)setTp(p);});return()=>{c=true;};},[tt]);
  useEffect(()=>{loadOkxSolTokens().catch(()=>{});},[]);
  const fetchQ=useCallback(async()=>{setQe('');if(!fa||parseFloat(fa)<=0||tokensEqual(ft,tt)){setQ(null);setQs(false);if(tokensEqual(ft,tt))setQe('Cannot swap a token for itself.');return;}if(!(fp>0)||!(tp>0)){setQ(null);setQs(false);return;}const g=parseFloat(fa)*fp/tp;const n=g*(1-TOTAL_FEE);setQ({engine:'estimate',outAmountDisplay:n.toFixed(n<.01?8:6),preview:true});setQs(false);},[fa,ft,tt,fp,tp]);
  useEffect(()=>{const t=setTimeout(fetchQ,QUOTE_DEBOUNCE_MS);return()=>clearTimeout(t);},[fetchQ]);
  const fbd=useMemo(()=>{if(ft?.chain==='solana')return ft.mint===WSOL_MINT?(sbl!=null?sbl/LAMPORTS_PER_SOL:null):ssb;if(ft?.chain==='evm'&&evmBal)return parseFloat(evmBal.formatted);return null;},[ft,sbl,ssb,evmBal]);
  const onMax=useCallback(()=>{if(fbd==null||fbd<=0)return;utRef.current=true;const d=Math.min(ft.decimals||6,9);if(ft?.chain==='solana'&&ft.mint===WSOL_MINT){setFa(maxSafeSolBalance(sbl).toFixed(d));return;}if(ft?.chain==='solana'){setFa(fbd.toFixed(d));return;}setFa(maxSafeAmount({balance:fbd,isNative:isNativeEvm}).toFixed(d));},[fbd,ft,sbl,isNativeEvm]);
  const applyB=useCallback(d=>{if(fp>0){utRef.current=true;setFa((d/fp).toFixed(Math.min(ft.decimals||6,9)));}},[fp,ft]);
  const applyS=useCallback(pct=>{if(fbd==null||fbd<=0)return;utRef.current=true;const d=Math.min(ft.decimals||6,9);let a=fbd*(pct/100);if(pct===100&&ft?.chain==='solana'&&ft.mint===WSOL_MINT)a=maxSafeSolBalance(sbl);else if(pct===100&&isNativeEvm)a=maxSafeAmount({balance:fbd,isNative:true});setFa(a.toFixed(d));},[fbd,ft,isNativeEvm,sbl]);
  const flip=useCallback(()=>{setFt(tt);setTt(ft);setFa('');setQ(null);setQe('');utRef.current=false;},[ft,tt]);
  const exec=useCallback(async()=>{if(!wcon){setPs(true);loginPrivy?.()||onConnectWallet?.();return;}if(!isSup){setSe('Pair not supported');setSs('error');return;}setSs('loading');setSe('');setStx(null);try{const raw=toRawAmount(fa,ft.decimals);if(!raw||raw==='0')throw new Error('Invalid amount');
    if(route==='okx-sol'){if(!pubkey)throw new Error('Connect Solana wallet');const sd=await fetchOkxSolSwap({fromMint:ft.mint,toMint:tt.mint,amount:raw,slippage:sl,userWallet:pubkey.toString()});const tx=await buildOkxSolTx({connection,userPubkey:pubkey,swapData:sd});const sig=await sendTx(tx,connection,{skipPreflight:false,maxRetries:3});setStx(sig);connection.confirmTransaction({signature:sig,blockhash:tx.message.recentBlockhash,lastValidBlockHeight:(await connection.getLatestBlockhash('confirmed')).lastValidBlockHeight},'confirmed').catch(()=>{});}
    else if(route==='okx-evm'){if(!effEvm||!wcRef.current)throw new Error('Connect EVM wallet');if(evmCid!==ft.chainId)await ensureChain(ft.chainId);const w=wcRef.current;const pc=pcRef.current;if(!w)throw new Error('Wallet not ready');const sd=await fetchOkxEvmSwap({chainId:ft.chainId,fromAddress:ft.address,toAddress:tt.address,amount:raw,slippage:sl,userWallet:effEvm});const tx=sd.tx;if(!tx?.to||!tx?.data)throw new Error('No tx data');
      if(!isNativeEvm){try{const ad=await fetchOkxEvmApproval({chainId:ft.chainId,tokenAddress:ft.address,amount:raw});if(ad?.dexContractAddress){let need=true;if(pc){try{const allowance=await pc.readContract({address:ft.address,abi:[{name:'allowance',type:'function',stateMutability:'view',inputs:[{name:'owner',type:'address'},{name:'spender',type:'address'}],outputs:[{type:'uint256'}]}],functionName:'allowance',args:[effEvm,ad.dexContractAddress]});need=safeBigInt(allowance)<safeBigInt(raw);}catch{need=false;}}if(need){const appr=ad.callData||('0x095ea7b3'+ad.dexContractAddress.slice(2).toLowerCase().padStart(64,'0')+'f'.repeat(64));const ah=await w.sendTransaction({to:ft.address,data:appr,value:BigInt(0)});if(pc){try{await pc.waitForTransactionReceipt({hash:ah,timeout:90000});}catch{}}}}}catch(e){throw new Error('Approval failed: '+(e.message||'unknown'));}}const hash=await w.sendTransaction({to:tx.to,data:tx.data,value:safeBigInt(tx.value),gas:tx.gas?safeBigInt(tx.gas):undefined});setStx(hash);}
    saveLastPair(ft,tt);setSs('success');setFa('');setQ(null);utRef.current=false;setTimeout(()=>{setSs('idle');setStx(null);},6000);}catch(e){setSe(e.message||'Swap failed');setSs('error');setTimeout(()=>{setSs('idle');setSe('');},5000);}},[wcon,isSup,fa,ft,tt,sl,route,pubkey,sendTx,connection,effEvm,evmCid,ensureChain,isNativeEvm,loginPrivy,onConnectWallet]);
  useEffect(()=>{if(wcon&&ps){setPs(false);exec();}},[wcon,ps,exec]);
  const txLink=useMemo(()=>{if(!stx)return null;if(route==='okx-sol')return'https://solscan.io/tx/'+stx;const ex={1:'etherscan.io',10:'optimistic.etherscan.io',56:'bscscan.com',137:'polygonscan.com',42161:'arbiscan.io',43114:'snowtrace.io',8453:'basescan.io'};return ex[ft?.chainId]?'https://'+ex[ft.chainId]+'/tx/'+stx:null;},[stx,route,ft]);
  const fuv=fa&&fp>0?parseFloat(fa)*fp:0;const tuv=quote&&tp>0?parseFloat(quote.outAmountDisplay)*tp:0;const td=quote?(quote.preview?'~'+quote.outAmountDisplay:quote.outAmountDisplay):'0.00';const tc=quote?C.green:C.muted2;const showBuy=ft&&/^(SOL|ETH|BNB|POL|AVAX|USDC|USDT)$/i.test(ft.symbol||'');const showSell=modeProp==='sell';

  return(<div style={{width:'100%',maxWidth:compact?'100%':520,margin:'0 auto'}}>
    {!compact&&<div style={{marginBottom:16}}><h1 style={{fontSize:22,fontWeight:800,color:'#fff',margin:0}}>Swap</h1><p style={{color:C.muted,fontSize:12,marginTop:4}}>Solana & 20+ EVM chains. Powered by OKX DEX.</p></div>}
    <div style={{background:compact?'transparent':C.card,border:compact?'none':'1px solid '+C.border,borderRadius:compact?0:18,padding:compact?0:18}}>
      <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:14}}><span style={{fontSize:11,color:C.muted,fontWeight:600}}>SLIPPAGE</span><div style={{display:'flex',gap:6}}>{[.1,.5,1.0].map(v=><button key={v} onClick={()=>setSl(v)} style={{padding:'6px 10px',borderRadius:6,fontSize:11,cursor:'pointer',background:sl===v?'rgba(0,229,255,.15)':'transparent',border:'1px solid '+(sl===v?'rgba(0,229,255,.4)':C.border),color:sl===v?C.accent:C.muted,fontFamily:'Syne, sans-serif',minHeight:32}}>{v}%</button>)}<button onClick={()=>setPeo(true)} style={{background:'none',border:'none',color:C.muted,cursor:'pointer',fontSize:16,marginLeft:6,padding:6}}>{'\u270E'}</button></div></div>
      {showBuy&&<div style={{marginBottom:8}}><div style={{fontSize:10,color:C.muted,fontWeight:700,marginBottom:6}}>QUICK BUY</div><div style={{display:'flex',gap:5}}>{presets.buy.map((a,i)=><button key={i} onClick={()=>applyB(a)} style={{flex:1,padding:'10px 4px',borderRadius:8,border:'1px solid '+C.border,background:C.card2,color:C.muted,fontWeight:700,fontSize:12,cursor:'pointer',fontFamily:'Syne, sans-serif',minHeight:40}}>${a}</button>)}</div></div>}
      {showSell&&fbd>0&&<div style={{marginBottom:8}}><div style={{fontSize:10,color:C.muted,fontWeight:700,marginBottom:6}}>QUICK SELL</div><div style={{display:'flex',gap:5}}>{presets.sell.map((p,i)=><button key={i} onClick={()=>applyS(p)} style={{flex:1,padding:'10px 4px',borderRadius:8,border:'1px solid '+C.border,background:C.card2,color:C.muted,fontWeight:700,fontSize:12,cursor:'pointer',fontFamily:'Syne, sans-serif',minHeight:40}}>{p===100?'MAX':p+'%'}</button>)}</div></div>}
      <div style={{background:C.card2,borderRadius:12,padding:14,border:'1px solid '+C.border,marginBottom:4}}><div style={{display:'flex',justifyContent:'space-between',marginBottom:8}}><span style={{fontSize:11,color:C.muted}}>YOU PAY</span>{fbd!=null&&<span style={{fontSize:11,color:C.muted}}>Balance: <span style={{color:C.text}}>{fmtTokenAmount(fbd)}</span></span>}</div><div style={{display:'flex',alignItems:'center',gap:8}}><button onClick={()=>setFso(true)} style={{display:'flex',alignItems:'center',gap:6,background:C.card3,border:'1px solid '+C.border,borderRadius:10,padding:'8px 10px',cursor:'pointer',flexShrink:0}}><TokenIcon token={ft} size={20}/><span style={{color:'#fff',fontWeight:700,fontSize:13}}>{ft?.symbol}</span><ChainBadge token={ft}/></button><input value={fa} onChange={e=>{utRef.current=true;setFa(e.target.value.replace(/[^0-9.]/g,''));}} placeholder="0.00" inputMode="decimal" style={{flex:1,background:'transparent',border:'none',fontSize:22,color:'#fff',textAlign:'right',outline:'none',fontFamily:'JetBrains Mono, monospace'}}/>{fbd>0&&<button onClick={onMax} style={{background:'rgba(0,229,255,.12)',border:'1px solid rgba(0,229,255,.25)',borderRadius:6,padding:'6px 10px',color:C.accent,fontSize:11,fontWeight:700,cursor:'pointer',flexShrink:0,fontFamily:'Syne, sans-serif'}}>MAX</button>}</div>{fuv>0&&<div style={{textAlign:'right',marginTop:5,fontSize:11,color:C.muted}}>{fmtUsd(fuv)}</div>}</div>
      <div style={{display:'flex',justifyContent:'center',margin:'8px 0'}}><button onClick={flip} style={{width:40,height:40,borderRadius:10,background:C.card3,border:'1px solid '+C.border,cursor:'pointer',color:C.accent,fontSize:14,display:'flex',alignItems:'center',justifyContent:'center'}}>{'\u21F5'}</button></div>
      <div style={{background:C.card2,borderRadius:12,padding:14,border:'1px solid '+C.border}}><div style={{display:'flex',justifyContent:'space-between',marginBottom:8}}><span style={{fontSize:11,color:C.muted}}>YOU RECEIVE</span></div><div style={{display:'flex',alignItems:'center',gap:8}}><button onClick={()=>setTso(true)} style={{display:'flex',alignItems:'center',gap:6,background:C.card3,border:'1px solid '+C.border,borderRadius:10,padding:'8px 10px',cursor:'pointer',flexShrink:0}}><TokenIcon token={tt} size={20}/><span style={{color:'#fff',fontWeight:700,fontSize:13}}>{tt?.symbol}</span><ChainBadge token={tt}/></button><div style={{flex:1,textAlign:'right',fontSize:22,color:tc,fontFamily:'JetBrains Mono, monospace'}}>{td}</div></div>{tuv>0&&<div style={{textAlign:'right',marginTop:5,fontSize:11,color:C.muted}}>{fmtUsd(tuv)}</div>}</div>
      {qe&&<div style={{marginTop:8,padding:10,background:'rgba(255,59,107,.1)',border:'1px solid rgba(255,59,107,.2)',borderRadius:8,fontSize:12,color:C.red}}>{qe}</div>}
      {!isSup&&<div style={{marginTop:10,padding:10,background:'rgba(255,149,0,.08)',border:'1px solid rgba(255,149,0,.25)',borderRadius:8,fontSize:12,color:'#ff9500'}}>Pair not supported.</div>}
      {quote&&fa&&<div style={{marginTop:12,background:'#050912',borderRadius:10,padding:12}}>{[['Platform fee',fuv>0?fmtUsd(fuv*PLATFORM_FEE):(PLATFORM_FEE*100)+'%'],['Anti-MEV',(SAFETY_FEE*100)+'%']].map(i=><div key={i[0]} style={{display:'flex',justifyContent:'space-between',padding:'3px 0',fontSize:11}}><span style={{color:C.muted}}>{i[0]}</span><span style={{color:C.text}}>{i[1]}</span></div>)}</div>}
      {se&&<div style={{marginTop:10,padding:10,background:'rgba(255,59,107,.1)',border:'1px solid rgba(255,59,107,.3)',borderRadius:8,fontSize:12,color:C.red}}>{se}</div>}
      {!wcon?<button onClick={()=>{setPs(true);loginPrivy?.()||onConnectWallet?.();}} style={{width:'100%',marginTop:14,padding:16,borderRadius:12,border:'none',background:'linear-gradient(135deg,#9945ff,#7c3aed)',color:'#fff',fontFamily:'Syne, sans-serif',fontWeight:800,fontSize:15,cursor:'pointer',minHeight:52}}>Sign in to Swap</button>
      :!hasNeeded?<button onClick={()=>{loginPrivy?.()||onConnectWallet?.();}} style={{width:'100%',marginTop:14,padding:16,borderRadius:12,border:'none',background:'linear-gradient(135deg,#9945ff,#7c3aed)',color:'#fff',fontFamily:'Syne, sans-serif',fontWeight:800,fontSize:15,cursor:'pointer',minHeight:52}}>Connect {needsSol?'Solana':'EVM'} wallet</button>
      :<button onClick={exec} disabled={ss==='loading'||!fa} style={{width:'100%',marginTop:14,padding:16,borderRadius:12,border:'none',background:ss==='success'?'linear-gradient(135deg,#00ffa3,#00b36b)':ss==='error'?'rgba(255,59,107,.2)':!fa?C.card2:C.buyGrad,color:!fa?C.muted2:'#fff',fontFamily:'Syne, sans-serif',fontWeight:800,fontSize:15,cursor:ss==='loading'?'not-allowed':'pointer',minHeight:52}}>{ss==='loading'?'Confirming...':ss==='success'?'Done!':ss==='error'?'Retry':!fa?'Enter amount':'Swap '+(ft?.symbol||'')+' → '+(tt?.symbol||'')}</button>}
      {ss==='loading'&&stuck&&<div style={{marginTop:10,padding:10,background:'rgba(255,59,107,.08)',border:'1px solid rgba(255,59,107,.25)',borderRadius:10,fontSize:11,color:C.muted}}><button onClick={()=>{setSs('idle');setSe('');}} style={{background:'transparent',border:'1px solid '+C.red,color:C.red,padding:'6px 12px',borderRadius:6,cursor:'pointer',fontFamily:'Syne, sans-serif',fontWeight:700}}>Reset</button></div>}
      {stx&&ss==='success'&&txLink&&<a href={txLink} target="_blank" rel="noreferrer" style={{display:'block',textAlign:'center',marginTop:10,fontSize:12,color:C.accent}}>View transaction</a>}
      <p style={{textAlign:'center',fontSize:10,color:C.muted2,marginTop:10}}>Non-custodial · Powered by OKX DEX</p>
    </div>
    <TokenSelectModal open={fso} onClose={()=>setFso(false)} onSelect={t=>{setFt(t);setQ(null);setQe('');}}/>
    <TokenSelectModal open={tso} onClose={()=>setTso(false)} onSelect={t=>{setTt(t);setQ(null);setQe('');}}/>
  </div>);
}

/* ===== TRADE DRAWER ===== */
export function TradeDrawer({open,onClose,mode='buy',coin,onConnectWallet,presets,onPresetsChange,presetUsd,presetPct,headerChain,onHeaderChainChange}){
  const{connected:solCon}=useWallet();const{isConnected:evmCon,chainId:evmCid}=useAccount();const nc=useMemo(()=>coin?normalizeToken(coin):null,[coin]);const pair=useMemo(()=>{const ws={solConnected:solCon,evmConnected:evmCon,evmChainId:evmCid};return nc?defaultTokenPair({mode,viewedToken:nc,lastFromToken:null,walletState:ws}):defaultTokenPair({mode,viewedToken:null,lastFromToken:null,walletState:ws});},[nc,mode,solCon,evmCon,evmCid]);const wk=useMemo(()=>{const id=nc?(nc.mint||nc.address||'tok'):'none';return id+'-'+mode;},[nc,mode]);const[sws,setSws]=useState('idle');const busy=sws==='loading';useEffect(()=>{if(open)setSws('idle');},[open]);const sc=useCallback(()=>{if(busy)return;onClose();},[busy,onClose]);useBodyScrollLock(open);useEscapeKey(open,sc);if(!open)return null;const sym=(nc&&nc.symbol)||(coin&&coin.symbol)||'';const img=(nc&&nc.logoURI)||(coin&&(coin.image||coin.logoURI));
  return(<><div onClick={sc} style={{position:'fixed',inset:0,zIndex:400,background:'rgba(0,0,0,.85)'}}/><div style={{position:'fixed',bottom:0,left:'50%',transform:'translateX(-50%)',width:'100%',maxWidth:560,zIndex:401,background:C.card,borderTop:'2px solid '+C.borderHi,borderRadius:'20px 20px 0 0',boxShadow:'0 -20px 60px rgba(0,0,0,.9)',maxHeight:'min(90vh, 100dvh)',display:'flex',flexDirection:'column',overflow:'hidden'}}><div style={{flexShrink:0,padding:'16px 20px 12px'}}><div onClick={sc} style={{width:40,height:4,background:C.muted2,borderRadius:2,margin:'0 auto 14px',cursor:busy?'default':'pointer',opacity:busy?.4:1}}/><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div style={{display:'flex',alignItems:'center',gap:10}}>{img&&<img src={img} alt="" style={{width:28,height:28,borderRadius:'50%'}} onError={e=>e.currentTarget.style.display='none'}/>}<div style={{color:mode==='buy'?C.accent:C.red,fontWeight:800,fontSize:17}}>{mode==='buy'?'Buy':'Sell'} {sym.toUpperCase()}</div></div><button onClick={sc} disabled={busy} style={{background:'none',border:'none',color:busy?C.muted2:C.muted,fontSize:26,cursor:busy?'not-allowed':'pointer',padding:4}}>x</button></div></div><div style={{flex:1,overflowY:'auto',padding:'4px 20px',paddingBottom:'calc(env(safe-area-inset-bottom) + 32px)'}}><SwapWidget key={wk} onConnectWallet={onConnectWallet} defaultFromToken={pair.fromToken} defaultToToken={pair.toToken} compact={true} mode={mode} presets={presets} onPresetsChange={onPresetsChange} onStatusChange={setSws}/></div></div></>);
}