import { Keypair } from "@solana/web3.js";
import * as fs from "fs";
import * as os from "os";
import * as path from "path"; 

export function loadKeypair(): Keypair {
  // Try env var first (for CI/GitHub Actions)
  if (process.env.KEYPAIR_JSON) {
    const secret = JSON.parse(process.env.KEYPAIR_JSON);
    return Keypair.fromSecretKey(Uint8Array.from(secret));
  }
  // Fall back to local file
  const keypairPath =
    process.env.KEYPAIR_PATH || path.join(os.homedir(), ".config/solana/id.json");
  if (!fs.existsSync(keypairPath)) {
    throw new Error(`Keypair not found at ${keypairPath}. Set KEYPAIR_JSON env var or KEYPAIR_PATH.`);
  }
  const secret = JSON.parse(fs.readFileSync(keypairPath, "utf-8"));
  return Keypair.fromSecretKey(Uint8Array.from(secret));
}

export function loadIdl(): any {
  // Try env var first (for CI)
  if (process.env.IDL_JSON) {
    return JSON.parse(process.env.IDL_JSON);
  }
  // Fall back to file generated by `anchor build`
  const idlPath = path.join(__dirname, "..", "target", "idl", "flipsy.json");
  if (!fs.existsSync(idlPath)) {
    throw new Error(`IDL not found at ${idlPath}. Run 'anchor build' first.`);
  }
  return JSON.parse(fs.readFileSync(idlPath, "utf-8"));
}

export function logBalance(label: string, lamports: number): void {
  console.log(`  ${label}: ${(lamports / 1e9).toFixed(4)} SOL`);
}

export async function airdropIfNeeded(
  connection: any,
  pubkey: any,
  minBalance: number = 1e9
): Promise<void> {
  const bal = await connection.getBalance(pubkey);
  if (bal < minBalance) {
    console.log(`Airdropping 2 SOL to ${pubkey.toBase58()}...`);
    const sig = await connection.requestAirdrop(pubkey, 2e9);
    await connection.confirmTransaction(sig);
  }
}
