name: List Methods

on:
  workflow_dispatch:

jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show instructions
        run: |
          node -e "const idl = require('./flipsy/target/idl/flipsy.json'); console.log(idl.instructions.map(i => i.name));"
