name: Crank

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  crank:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: cd flipsy/scripts && npm install

      - name: Run cranker
        env:
          DEPLOYER_SEED: ${{ secrets.DEPLOYER_SEED }}
          REACT_APP_FLIPSY_PROGRAM_ID: ${{ secrets.REACT_APP_FLIPSY_PROGRAM_ID }}
        run: cd flipsy/scripts && npx ts-node crank-once.ts
